//! `bedrock check` — validate complete situation source and its resident
//! projection (SPINE §4).
//!
//! - C1 placement + generated AGENTS.md drift
//! - C2 YAML syntax profile
//! - C3 JSON-LD profile, namespace membership, no blank nodes
//! - C4 namespace schemas
//! - C5 complete-source edge resolution
//! - C6 deterministic generated bytes
//! - C7 emitted resident TriG parse-back equivalence
//! - C8 done requires a witness
//! - C9 every source carries a base type
//! - C10 installed base-file digest skew
//! - C11 resident projection closes over vertex edges
//! - C12 registered opaque mount boundary

use crate::compile;
use crate::contextreg::{ContextRegistry, GRAPH_NAMESPACES, NAMESPACES, OPERATING_REF_PATH};
use crate::errors::{Fatal, Violation};
use crate::generate;
use crate::schema::SchemaRegistry;
use oxrdf::{NamedOrBlankNode, Quad, Term};
use serde_json::Value;
use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

pub struct Compiled {
    /// The resident quads emitted into root AGENTS.md.
    pub quads: Vec<Quad>,
    /// The single generated artifact: root AGENTS.md = comment preamble +
    /// resident TriG projection — the file the harness injects.
    pub agents_md: String,
    /// Per-resident-vertex projected-face sizes (advisory soft budget).
    pub faces: Vec<Face>,
    /// Every YAML-LD source validated under situation/, resident or cold.
    pub source_files: usize,
    /// Counts that make the resident/cold boundary visible in CI.
    pub projection: ProjectionStats,
}

/// Resident/cold projection counts (0.6.0). All sources are validated; only
/// the current working set is emitted into AGENTS.md.
#[derive(Default)]
pub struct ProjectionStats {
    pub active_plans: usize,
    pub draft_plans: usize,
    pub done_plans: usize,
    pub abandoned_plans: usize,
    pub unknown_plans: usize,
    pub resident_decisions: usize,
    pub cold_records: usize,
    pub cold_references: usize,
}

/// One resident vertex's projected face: the chars every agent context pays
/// for. Cold plan payload, episodic records, references, comments, and body
/// prose do not count.
pub struct Face {
    pub rel: String,
    pub chars: usize,
}

/// The soft resident-face budget: 4096 chars ≈ 1k tokens. Advisory, never
/// failing — the target band is 500–1000 tokens.
pub const SOFT_FACE_BUDGET_CHARS: usize = 4096;

const PLAN_ROUTING_FIELDS: [&str; 10] = [
    "label",
    "intent",
    "consumes",
    "requires",
    "references",
    "produces",
    "member-of",
    "oracle",
    "source",
    "path",
];

/// The set of source yamlld files under situation/ with their namespace.
struct SourceFile {
    rel: PathBuf,       // repo-relative, e.g. situation/definition/a.yamlld
    ns: Option<String>, // Some("definition") or None (references/)
    text: String,
}

/// Run all rules on `root`. Returns violations and the resident projection.
pub fn run(root: &Path) -> Result<(Vec<Violation>, Option<Compiled>), Fatal> {
    let (mut out, compiled) = collect(root)?;
    if let Some(c) = &compiled {
        drift_checks(root, c, &mut out);
    }
    // C10: installed base files (schemas, context, operating reference)
    // must match this binary's embedded copies.
    digest_skew_checks(root, &mut out);
    Ok((out, compiled))
}

/// Everything except the drift check (C1: committed AGENTS.md — the resident
/// projection — vs regenerated). `init`/`adopt` write artifacts first, then
/// run the full `run()`.
pub fn collect(root: &Path) -> Result<(Vec<Violation>, Option<Compiled>), Fatal> {
    let mut out: Vec<Violation> = Vec::new();
    let seed = resolve_seed(root)?;
    let registry = ContextRegistry::load(Some(&seed))?;
    let schemas = SchemaRegistry::load(Some(&seed))?;

    // Registrations are discovered before C1 judges unknown situation roots.
    let mount_candidates = crate::mount::discover(root);
    let mount_names = crate::mount::exclusion_names(&mount_candidates);
    let sources = scan_situation(root, &mount_names, &mut out);
    scan_agents_md(root, &mount_names, &mut out);
    let registrations = crate::mount::validate(root, &mount_candidates, &mut out);

    // Source quads are the validation dataset. Resident quads are the
    // deterministic working-set projection injected into every agent.
    let mut source_quads: Vec<Quad> = Vec::new();
    let mut resident_quads: Vec<Quad> = Vec::new();
    let mut faces: Vec<Face> = Vec::new();
    let mut projection = ProjectionStats::default();

    for f in &sources {
        // C2
        let parsed = compile::parse_yaml(&f.text, &rel(&f.rel));
        out.extend(parsed.violations.iter().cloned());
        let Some(value) = &parsed.value else {
            continue;
        };

        // C3 profile
        out.extend(compile::ld_profile(value, &rel(&f.rel), &f.text, &registry));

        // C3 expansion + graph membership
        let ns_name: Option<&str> = f.ns.as_deref();
        match compile::expand(value, &rel(&f.rel), &f.text, &registry) {
            Ok(quads) => match compile::remap_graphs(quads, ns_name, &rel(&f.rel), &f.text) {
                Ok(mut quads) => {
                    // C4
                    out.extend(schemas.validate(ns_name, value, &rel(&f.rel), &f.text));
                    // C5 mounted-path subject shape; ordinary edge resolution
                    // remains the full-source pass below.
                    out.extend(c5_reflect_subject(
                        ns_name,
                        value,
                        &rel(&f.rel),
                        &f.text,
                        root,
                        &registrations,
                    ));
                    // C8 witness gate (plan + record namespace)
                    out.extend(c8_witness_gate(ns_name, value, &rel(&f.rel), &f.text));
                    // C9 base-type intersection
                    out.extend(c9_base_type(value, &rel(&f.rel), &f.text));

                    // Every source vertex has a deterministic edit/read
                    // pointer in the validation dataset. The projection
                    // retains it only when the vertex is resident.
                    add_document_quad(value, &mut quads, &f.rel);

                    if let Some(projected) =
                        project_resident(ns_name, value, &quads, &mut projection)
                    {
                        faces.push(Face {
                            rel: rel(&f.rel),
                            chars: projected_face_chars(ns_name, value),
                        });
                        resident_quads.extend(projected);
                    }
                    source_quads.extend(quads);
                }
                Err(vs) => out.extend(vs),
            },
            Err(vs) => out.extend(vs),
        }
    }

    // ---------- C5: full-source edge resolution ----------
    let source_vertex_ids = vertex_ids(&source_quads);
    check_edges(&source_quads, &source_vertex_ids, root, &mut out);

    // Generated pointer linkage is resident Bedrock metadata. Mount graph
    // content is never included in source or resident datasets.
    resident_quads.extend(crate::mount::linkage_quads(&registrations));

    // ---------- C11: resident projection integrity ----------
    let resident_vertex_ids = vertex_ids(&resident_quads);
    check_resident_edges(
        &resident_quads,
        &resident_vertex_ids,
        &source_vertex_ids,
        &mut out,
    );

    // ---------- compile the resident projection ----------
    let sorted = compile::sort_quads(resident_quads);
    let raw_trig = compile::serialize_trig(&sorted).map_err(Fatal)?;

    // Preamble (# comments) + resident TriG projection; the digest pins the
    // projected body bytes. C7 reads the exact file agents read.
    let digest = generate::digest_hex(&raw_trig);
    let agents = generate::generate_agents_md(root, &sorted, &String::from_utf8_lossy(&raw_trig));
    let agents = generate::stamp_digest(&agents, &digest);
    if let Some(v) = compile::verify_parseback(&sorted, agents.as_bytes()) {
        out.push(v);
    }

    let compiled = Compiled {
        quads: sorted,
        agents_md: agents,
        faces,
        source_files: sources.len(),
        projection,
    };
    Ok((out, Some(compiled)))
}

/// Drift check: committed AGENTS.md (the resident projection) must byte-match
/// regeneration. One artifact, one drift rule.
pub fn drift_checks(root: &Path, compiled: &Compiled, out: &mut Vec<Violation>) {
    // C1: root AGENTS.md hand-edit drift.
    let agents_path = root.join("AGENTS.md");
    match std::fs::read(&agents_path) {
        Ok(existing) if existing != compiled.agents_md.as_bytes() => out.push(Violation::new(
            "C1",
            "AGENTS.md",
            1,
            "root AGENTS.md (the resident projection) is out of date or hand-edited; run bedrock build (it is generated — never hand-edited, SPINE §5)"
                .to_string(),
        )),
        Ok(_) => {}
        Err(_) => {} // absent root AGENTS.md is not drift (init/adopt generate it)
    }
}

/// Resolve the seed directory for `check`/`build`: `BEDROCK_SEED` override,
/// else `<root>/seed` (the copy `init`/`adopt` install into the consumer).
///
/// Deliberately NO embedded fallback here: a repo under `check`/`build` must
/// carry its own installed seed (SPINE §2/§8) — the embedded copy is the
/// `init`/`adopt` bootstrap, resolved separately in `install.rs`.
pub fn resolve_seed(root: &Path) -> Result<PathBuf, Fatal> {
    if let Ok(v) = std::env::var("BEDROCK_SEED") {
        if !v.is_empty() {
            let p = PathBuf::from(v);
            if !p.is_dir() {
                return Err(Fatal(format!(
                    "BEDROCK_SEED points at a missing directory: {}",
                    p.display()
                )));
            }
            return Ok(p);
        }
    }
    let p = root.join("seed");
    if !p.is_dir() {
        return Err(Fatal(format!(
            "{}: no seed/ directory (SPINE §2/§8). Run `bedrock init` to install it, or set BEDROCK_SEED",
            p.display()
        )));
    }
    Ok(p)
}

/// C1 placement: walk situation/ per §3.
fn scan_situation(
    root: &Path,
    mount_names: &BTreeSet<String>,
    out: &mut Vec<Violation>,
) -> Vec<SourceFile> {
    let sit = root.join("situation");
    let mut sources = Vec::new();
    let Ok(entries) = std::fs::read_dir(&sit) else {
        out.push(Violation::new(
            "C1",
            "situation",
            1,
            "situation/ missing or unreadable",
        ));
        return sources;
    };
    let mut root_entries: Vec<PathBuf> = Vec::new();
    for e in entries.flatten() {
        root_entries.push(e.path());
    }
    root_entries.sort();
    for p in root_entries {
        let name = p.file_name().unwrap_or_default();
        let name = name.to_str().unwrap_or_default();
        let is_hidden = name.starts_with('.');
        if p.is_dir() {
            if NAMESPACES.contains(&name) {
                scan_namespace(root, &p, out, &mut sources);
            } else if mount_names.contains(name) {
                // Registered opaque exclusion. C12 owns its narrow traversal.
            } else {
                out.push(Violation::new(
                    "C1",
                    format!("situation/{name}"),
                    1,
                    format!("only the six base namespaces plus registered opaque mounts are allowed, got unregistered directory `{name}`"),
                ));
            }
        } else if name == "graph.trig" {
            out.push(Violation::new(
                "C1",
                "situation/graph.trig",
                1,
                "legacy generated artifact (0.4.0 compiles the graph into the root AGENTS.md — one artifact); `bedrock build` deletes it"
                    .to_string(),
            ));
        } else if is_hidden {
            // dot files (e.g. .gitkeep) are legal
        } else {
            out.push(Violation::new(
                "C1",
                format!("situation/{name}"),
                1,
                "unexpected file directly under situation/; only the six base namespace directories live here"
                    .to_string(),
            ));
        }
    }
    sources
}

fn scan_namespace(
    root: &Path,
    ns_dir: &Path,
    out: &mut Vec<Violation>,
    sources: &mut Vec<SourceFile>,
) {
    let ns = ns_dir
        .file_name()
        .unwrap_or_default()
        .to_str()
        .unwrap_or_default()
        .to_string();
    let mut entries: Vec<PathBuf> = std::fs::read_dir(ns_dir)
        .map(|rd| rd.flatten().map(|e| e.path()).collect())
        .unwrap_or_default();
    entries.sort();
    for p in entries {
        let name = p
            .file_name()
            .unwrap_or_default()
            .to_str()
            .unwrap_or_default();
        let rel = rel(p.strip_prefix(root).unwrap_or(&p));
        if ns == "references" {
            // references/ may nest freely and hold non-YAML-LD files (§3).
            push_files_recursive(root, &p, sources);
            continue;
        }
        if p.is_dir() {
            out.push(Violation::new(
                "C1",
                &rel,
                1,
                "namespace directories (definition|architecture|risk|plan|record) hold flat vertex files only — no subdirectories"
                    .to_string(),
            ));
            continue;
        }
        if name.starts_with('.') {
            continue; // .gitkeep etc.
        }
        if name.ends_with(".trig") {
            out.push(Violation::new(
                "C1",
                &rel,
                1,
                format!("legacy generated artifact `{name}` (0.4.0 compiles the graph into the root AGENTS.md — one artifact); `bedrock build` deletes it"),
            ));
            continue;
        }
        if !name.ends_with(".yamlld") {
            out.push(Violation::new(
                "C1",
                &rel,
                1,
                format!("file `{name}` is not a vertex; namespace directories hold flat `<local-name>.yamlld` vertices"),
            ));
            continue;
        }
        {
            let text = std::fs::read_to_string(&p).unwrap_or_default();
            sources.push(SourceFile {
                rel: strip_situation_rel(root, &p),
                ns: Some(ns.clone()),
                text,
            });
        }
        // .trig files are generated artifacts; C6 verifies them.
    }
}

fn push_files_recursive(root: &Path, dir: &Path, sources: &mut Vec<SourceFile>) {
    if dir.is_dir() {
        let mut es: Vec<PathBuf> = std::fs::read_dir(dir)
            .map(|rd| rd.flatten().map(|e| e.path()).collect())
            .unwrap_or_default();
        es.sort();
        for p in es {
            push_files_recursive(root, &p, sources);
        }
    } else if dir.extension().map(|e| e == "yamlld").unwrap_or(false) {
        let text = std::fs::read_to_string(dir).unwrap_or_default();
        sources.push(SourceFile {
            rel: strip_situation_rel(root, dir),
            ns: None,
            text,
        });
    }
}

fn strip_situation_rel(root: &Path, p: &Path) -> PathBuf {
    // situation/<ns>/<name>.yamlld → situation/<ns>/<name>.yamlld (repo-relative)

    p.strip_prefix(root).unwrap_or(p).to_path_buf()
}

fn rel(p: impl AsRef<Path>) -> String {
    p.as_ref().to_string_lossy().into_owned()
}

/// Add the automatic pointer from a source vertex to its own file. It lives
/// in the full validation dataset; projection keeps it only for residents.
fn add_document_quad(value: &Value, quads: &mut Vec<Quad>, source: &Path) {
    let Some(id) = value.get("@id").and_then(Value::as_str) else {
        return;
    };
    let Some(graph_name) = quads.first().map(|q| q.graph_name.clone()) else {
        return;
    };
    quads.push(Quad {
        subject: NamedOrBlankNode::NamedNode(
            oxrdf::NamedNode::new(id).expect("schema requires an absolute vertex @id"),
        ),
        predicate: oxrdf::NamedNode::new(crate::contextreg::predicate("document"))
            .expect("canonical document predicate"),
        object: Term::NamedNode(
            oxrdf::NamedNode::new(format!(
                "{}{}",
                crate::contextreg::PATH_PREFIX,
                source.display()
            ))
            .expect("repo-relative source path is a valid IRI"),
        ),
        graph_name,
    });
}

/// Project one fully validated source vertex into the resident working set.
///
/// - definition/architecture/risk are resident;
/// - only active Plans are resident, as routing faces;
/// - only Decisions are resident from record/;
/// - references/ YAML-LD is cold (refer through paths).
fn project_resident(
    ns: Option<&str>,
    value: &Value,
    quads: &[Quad],
    stats: &mut ProjectionStats,
) -> Option<Vec<Quad>> {
    match ns {
        Some("plan") => match plan_state(value) {
            Some("active") => {
                stats.active_plans += 1;
                Some(project_active_plan(value, quads))
            }
            Some("draft") => {
                stats.draft_plans += 1;
                None
            }
            Some("done") => {
                stats.done_plans += 1;
                None
            }
            Some("abandoned") => {
                stats.abandoned_plans += 1;
                None
            }
            _ => {
                stats.unknown_plans += 1;
                None
            }
        },
        Some("record") => {
            if type_iris(value)
                .iter()
                .any(|iri| crate::contextreg::is_ontology_type(iri, "Decision"))
            {
                stats.resident_decisions += 1;
                Some(quads.to_vec())
            } else {
                stats.cold_records += 1;
                None
            }
        }
        Some(_) => Some(quads.to_vec()),
        None => {
            stats.cold_references += 1;
            None
        }
    }
}

/// An active Plan contributes routing information, never its execution
/// payload. Acceptance criteria, tasks, witnesses, reflection depth,
/// residual, statement, and body remain in the source document.
fn project_active_plan(value: &Value, quads: &[Quad]) -> Vec<Quad> {
    let mut projected: Vec<Quad> = quads
        .iter()
        .filter(|q| {
            q.predicate == oxrdf::vocab::rdf::TYPE
                || crate::contextreg::is_predicate(q.predicate.as_str(), "document")
                || PLAN_ROUTING_FIELDS
                    .iter()
                    .any(|field| crate::contextreg::is_predicate(q.predicate.as_str(), field))
        })
        .cloned()
        .collect();

    if let Some(id) = value.get("@id").and_then(Value::as_str)
        && let Some(graph_name) = quads.first().map(|q| q.graph_name.clone())
    {
        projected.push(Quad {
            subject: NamedOrBlankNode::NamedNode(
                oxrdf::NamedNode::new(id).expect("schema requires an absolute vertex @id"),
            ),
            predicate: oxrdf::NamedNode::new(crate::contextreg::predicate("state"))
                .expect("canonical state predicate"),
            object: Term::Literal(oxrdf::Literal::new_simple_literal("active")),
            graph_name,
        });
    }
    projected
}

fn plan_state(value: &Value) -> Option<&str> {
    value
        .get("disposition")
        .and_then(|d| d.get("state"))
        .and_then(Value::as_str)
}

fn vertex_ids(quads: &[Quad]) -> BTreeSet<String> {
    quads
        .iter()
        .filter_map(|q| match &q.subject {
            NamedOrBlankNode::NamedNode(n) => Some(n.as_str().to_string()),
            NamedOrBlankNode::BlankNode(_) => None,
        })
        .collect()
}

/// Advisory resident-face measure. Active Plans are measured from the exact
/// routing fields their projection permits; other resident vertices are
/// measured from their YAML face with body removed.
fn projected_face_chars(ns: Option<&str>, value: &Value) -> usize {
    let projected = if ns == Some("plan") {
        let mut out = serde_json::Map::new();
        let keys = ["@context", "@id", "@type"];
        if let Some(source) = value.as_object() {
            for key in keys.into_iter().chain(PLAN_ROUTING_FIELDS.iter().copied()) {
                if let Some(v) = source.get(key) {
                    out.insert(key.to_string(), v.clone());
                }
            }
        }
        out.insert("state".to_string(), Value::String("active".to_string()));
        Value::Object(out)
    } else {
        let mut out = value.clone();
        if let Some(obj) = out.as_object_mut() {
            obj.remove("body");
        }
        out
    };
    serde_norway::to_string(&projected)
        .map(|s| s.chars().count())
        .unwrap_or_default()
}

/// C1 global AGENTS.md confinement. Registered mount roots are traversed only
/// by C12, which rejects nested AGENTS.md without exposing other contents.
fn scan_agents_md(root: &Path, mount_names: &BTreeSet<String>, out: &mut Vec<Violation>) {
    let mut stack = vec![root.to_path_buf()];
    while let Some(dir) = stack.pop() {
        let Ok(entries) = std::fs::read_dir(&dir) else {
            continue;
        };
        for e in entries.flatten() {
            let p = e.path();
            let name = e.file_name().to_str().unwrap_or_default().to_string();
            if p.is_dir() {
                if mount_names.contains(&name)
                    && p.parent() == Some(root.join("situation").as_path())
                {
                    continue;
                }
                // do not descend into target/, .git, or quarantined test rigs:
                // fixtures are rig material (they plant deliberate violations
                // to test the rules) and never carry repo law.
                if name == ".git" || name == "target" {
                    continue;
                }
                if name == "fixtures" && dir.file_name().and_then(|n| n.to_str()) == Some("tests") {
                    continue;
                }
                stack.push(p);
            } else if name == "AGENTS.md" && p != root.join("AGENTS.md") {
                let rel = p.strip_prefix(root).unwrap_or(&p);
                out.push(Violation::new(
                    "C1",
                    rel.to_string_lossy().into_owned(),
                    1,
                    "AGENTS.md outside the repo root — exactly ONE generated AGENTS.md per repo, at root (SPINE §3, §5)"
                        .to_string(),
                ));
            }
        }
    }
}

/// C5: ReflectVerdict subjects may be authored base vertices or existing
/// paths canonically contained by one registered mount.
fn c5_reflect_subject(
    ns: Option<&str>,
    value: &Value,
    rel: &str,
    src: &str,
    root: &Path,
    registrations: &[crate::mount::Registration],
) -> Vec<Violation> {
    if ns != Some("record")
        || !type_iris(value)
            .iter()
            .any(|iri| crate::contextreg::is_ontology_type(iri, "ReflectVerdict"))
    {
        return Vec::new();
    }
    let Some(subject) = value.get("subject").and_then(Value::as_str) else {
        return Vec::new();
    };
    let Some(path) = crate::contextreg::path_from_iri(subject) else {
        return Vec::new();
    };
    if crate::mount::contains_registered_path(root, Path::new(path), registrations) {
        Vec::new()
    } else {
        vec![Violation::new(
            "C5",
            rel,
            crate::errors::line_of(src, subject),
            format!("ReflectVerdict subject path `{path}` is not contained by a registered mount"),
        )]
    }
}

/// C8 (witness gate, base protocol): a Plan or ReflectVerdict whose
/// `disposition.state` is `done` must carry at least one `witnesses` entry —
/// no witness, no done. Judged on the parsed vertex so the violation is
/// line-cited at the `done` (the source schema has already validated shape).
fn c8_witness_gate(ns: Option<&str>, value: &Value, rel: &str, src: &str) -> Vec<Violation> {
    let gate_type = match ns {
        Some("plan") => "Plan",
        Some("record") => "ReflectVerdict",
        _ => return Vec::new(),
    };
    let types = type_iris(value);
    if !types
        .iter()
        .any(|iri| crate::contextreg::is_ontology_type(iri, gate_type))
    {
        return Vec::new();
    }
    let Some(state) = value
        .get("disposition")
        .and_then(|d| d.get("state"))
        .and_then(|s| s.as_str())
    else {
        return Vec::new(); // no disposition declared → no gate
    };
    if state != "done" {
        return Vec::new();
    }
    let witnesses = value
        .get("witnesses")
        .and_then(|w| w.as_array())
        .map(|a| a.len())
        .unwrap_or(0);
    if witnesses == 0 {
        vec![Violation::new(
            "C8",
            rel,
            crate::errors::line_of(src, "done"),
            "disposition is `done` with zero witnesses — no witness, no done (base protocol chain rule; a witness is a retained CI-run-URL observation, never a local attestation)",
        )]
    } else {
        Vec::new()
    }
}

/// C9 (base-type, base protocol): every vertex's `@type` set must intersect
/// the closed base @type set. Repo archetypes may ride alongside a base type
/// in the same array, never alone; they never redefine a base term.
fn c9_base_type(value: &Value, rel: &str, src: &str) -> Vec<Violation> {
    let types = type_iris(value);
    if types.is_empty() {
        return Vec::new(); // missing/malformed @type is a C4/schema concern
    }
    if types.iter().any(|iri| crate::contextreg::is_base_type(iri)) {
        return Vec::new();
    }
    let bad = types.first().cloned().unwrap_or_default();
    vec![Violation::new(
        "C9",
        rel,
        crate::errors::line_of(src, &bad),
        format!(
            "vertex {bad} carries no base @type — every vertex must carry at least one of (Invariant|Breadcrumb|Term|Identity|SituationStructure|Risk|Plan|EpochRecord|DeployRecord|ReflectVerdict|Decision|ExpansionMount); repo archetypes ride alongside, never alone"
        ),
    )]
}

/// Extract the `@type` IRIs (string or array) of a parsed vertex.
fn type_iris(value: &Value) -> Vec<String> {
    match value.get("@type") {
        Some(Value::String(s)) => vec![s.clone()],
        Some(Value::Array(a)) => a
            .iter()
            .filter_map(|x| x.as_str().map(str::to_string))
            .collect(),
        _ => Vec::new(),
    }
}

/// C10: every Bedrock-owned installed base file, including the substrate
/// checker lock, byte-matches this binary's canonical stamped form.
fn digest_skew_checks(root: &Path, out: &mut Vec<Violation>) {
    let seed = &crate::embedded::SEED;
    use crate::provenance::Kind;
    for ns in GRAPH_NAMESPACES {
        let rel = format!("seed/schemas/{ns}.json");
        // SEED is rooted at `seed/`, so the in-tree path has no `seed/` prefix.
        let embedded = seed
            .get_file(format!("schemas/{ns}.json").as_str())
            .map(|f| f.contents());
        check_base_blob(root, out, &rel, embedded, Kind::Json);
    }
    let embedded_ctx = seed.get_file("context.yamlld").map(|f| f.contents());
    check_base_blob(root, out, "seed/context.yamlld", embedded_ctx, Kind::Hash);
    let embedded_op = Some(include_str!("embedded/bedrock-operating.md").as_bytes());
    check_base_blob(root, out, OPERATING_REF_PATH, embedded_op, Kind::Hash);
    let lock_path = root.join(crate::contextreg::SUBSTRATE_LOCK_PATH);
    if root.join("seed").is_dir() && !lock_path.is_file() {
        out.push(Violation::new(
            "C10",
            crate::contextreg::SUBSTRATE_LOCK_PATH,
            0,
            "installed substrate lock is missing — run `bedrock update`; existing consumer workflows require a one-time manual migration",
        ));
    } else {
        let embedded_lock = seed.get_file("substrate-lock.json").map(|f| f.contents());
        check_base_blob(
            root,
            out,
            crate::contextreg::SUBSTRATE_LOCK_PATH,
            embedded_lock,
            Kind::Json,
        );
    }
}

fn check_base_blob(
    root: &Path,
    out: &mut Vec<Violation>,
    rel: &str,
    embedded: Option<&[u8]>,
    kind: crate::provenance::Kind,
) {
    let Some(embedded) = embedded else {
        return; // the embedded copy is compile-time; absence here is a build defect
    };
    let p = root.join(rel);
    if !p.exists() {
        return;
    }
    // C10 coherence: the canonical expected form is the embedded
    // template + the provenance stamp rendered for the current binary
    // version — install, update, and this comparison use the same render, so
    // raw embedded bytes ≠ installed bytes and a stale stamp flags here.
    let version = crate::provenance::current_version();
    let expected = crate::provenance::render(kind, version, embedded);
    match std::fs::read(&p) {
        Ok(installed) if installed != expected => out.push(Violation::new(
            "C10",
            rel,
            0,
            format!(
                "installed {rel} differs from this binary's canonical stamped form (embedded template + provenance stamp v{version}) — run `bedrock update` to refresh the installed base files; if the base itself is wrong, file an issue: {} (base protocol C10; a version-skewed stamp is exactly this violation)",
                crate::provenance::REPO_URL,
            ),
        )),
        _ => {}
    }
}

/// C5: every source IRI edge resolves to a source vertex @id or repo path.
fn check_edges(
    all_quads: &[Quad],
    vertex_ids: &BTreeSet<String>,
    root: &Path,
    out: &mut Vec<Violation>,
) {
    for q in all_quads {
        if q.predicate == oxrdf::vocab::rdf::TYPE {
            continue; // class IRIs are vocabulary, not edges
        }
        let Term::NamedNode(obj) = &q.object else {
            continue;
        };
        let target = obj.as_str();
        if vertex_ids.contains(target) {
            continue;
        }
        if let Some(path) = crate::contextreg::path_from_iri(target) {
            if root.join(path).exists() {
                continue;
            }
            out.push(Violation::new(
                "C5",
                "situation",
                1,
                format!("edge target {target} → repo path `{path}` does not exist"),
            ));
            continue;
        }
        out.push(Violation::new(
            "C5",
            "situation",
            1,
            format!("edge target {target} is neither a vertex @id in this repo's situation source nor an existing repo path"),
        ));
    }
}

/// C11: the resident projection is closed under vertex edges. A resident
/// node may not point by vertex IRI at a cold source because the injected
/// graph would expose an edge whose target is absent. Historical relations
/// use path pointers; durable relations target resident knowledge.
fn check_resident_edges(
    resident_quads: &[Quad],
    resident_vertex_ids: &BTreeSet<String>,
    source_vertex_ids: &BTreeSet<String>,
    out: &mut Vec<Violation>,
) {
    for q in resident_quads {
        if q.predicate == oxrdf::vocab::rdf::TYPE {
            continue;
        }
        let Term::NamedNode(target) = &q.object else {
            continue;
        };
        if resident_vertex_ids.contains(target.as_str())
            || !source_vertex_ids.contains(target.as_str())
        {
            continue;
        }
        out.push(Violation::new(
            "C11",
            "situation",
            1,
            format!(
                "resident vertex {} points to cold vertex {} via {} — the injected graph must be closed under vertex edges; use a repo-path pointer for history or promote the target into resident knowledge",
                q.subject, target, q.predicate
            ),
        ));
    }
}
