//! Provenance stamps — every file bedrock installs or generates announces it
//! is machine-owned and routes base changes to the owning repo (0.2.1).
//!
//! Stamps carry the version, so the raw embedded template bytes ≠ the
//! installed bytes. The canonical expected form of a base file is
//! `render(kind, version, template)`, used identically by install, update,
//! AND the C10 digest-skew comparison. Render is idempotent per version: an
//! input that already carries the same-version stamp passes through
//! unchanged; a missing or stale-version stamp is normalized to the current
//! version. A version-skewed stamp is exactly what C10 flags and what
//! `bedrock update` repairs.

use crate::errors::Fatal;
use std::path::Path;

/// The owning repository: base defects and friction route here.
pub const REPO_URL: &str = "https://github.com/cleverunicornz/bedrock";

/// The shared provenance sentence every stamp names, rendered for `version`
/// (no `#` prefix — each `Kind` supplies its own comment syntax).
pub fn provenance_text(version: &str) -> String {
    format!(
        "Installed by bedrock v{} \u{2014} DO NOT EDIT. This file is owned by the tool. Base \
         changes: file an issue or PR at {REPO_URL}. Local refresh: bedrock update.",
        version
    )
}

/// A file class in the stamp grammar.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Kind {
    /// `#` comment header for .md/.yamlld/.yml installed files (operating
    /// reference, context, workflow template, playbooks).
    Hash,
    /// `"$comment"` key for the JSON base schemas.
    Json,
    /// One-line `# seeded by bedrock vX` — floor vertices in
    /// `situation/definition/`, which repos own and extend around.
    Seed,
    /// First-line HTML comment on the generated AGENTS.md.
    Html,
    /// First-line `#` comment on generated TriG (graph.trig, plan .trig).
    Trig,
}

/// The header for `kind` rendered for `version` (no trailing newline).
pub fn header(kind: Kind, version: &str) -> String {
    match kind {
        Kind::Hash => format!("# {}", provenance_text(version)),
        Kind::Json => format!("  \"$comment\": \"{}\",", provenance_text(version)),
        Kind::Seed => format!("# seeded by bedrock v{version}"),
        Kind::Html => {
            format!("<!-- generated by bedrock v{version}; do not edit; source: situation/ -->")
        }
        Kind::Trig => format!("# generated by bedrock v{version}; do not edit; source: situation/"),
    }
}

/// The current binary's version — the version every stamp is rendered for at
/// runtime (install, update, and the C10 comparison all use this).
pub fn current_version() -> &'static str {
    env!("CARGO_PKG_VERSION")
}

/// True when `base` already carries the exact `version` stamp of `kind`.
fn already_stamped(kind: Kind, version: &str, base: &[u8]) -> bool {
    match kind {
        Kind::Json => {
            base.starts_with(b"{\n") && base[2..].starts_with(header(kind, version).as_bytes())
        }
        _ => base.starts_with(header(kind, version).as_bytes()),
    }
}

/// Render the canonical stamped form of `base` for `version` (idempotent per
/// version): a correct-version stamp passes through, a missing or stale
/// stamp is normalized to exactly one header for the current version.
pub fn render(kind: Kind, version: &str, base: &[u8]) -> Vec<u8> {
    if already_stamped(kind, version, base) {
        return base.to_vec();
    }
    let h = header(kind, version).into_bytes();
    let stripped = strip_one_stamp(kind, base);
    let mut out = Vec::with_capacity(h.len() + stripped.len() + 1);
    match kind {
        Kind::Json => {
            // Splice the `$comment` key right after the opening `{` line.
            match stripped.iter().position(|&b| b == b'\n') {
                Some(i) => {
                    out.extend_from_slice(&stripped[..=i]); // "{\n"
                    out.extend_from_slice(&h);
                    out.push(b'\n');
                    out.extend_from_slice(&stripped[i + 1..]);
                }
                None => {
                    out.extend_from_slice(&h);
                    out.push(b'\n');
                    out.extend_from_slice(&stripped);
                }
            }
        }
        _ => {
            out.extend_from_slice(&h);
            out.push(b'\n');
            out.extend_from_slice(&stripped);
        }
    }
    out
}

/// Drop at most one leading same-kind stamp (any version). For Hash/Seed a
/// leading line plus its newline; for Json the `$comment` key line that
/// follows the opening `{`.
fn strip_one_stamp(kind: Kind, base: &[u8]) -> Vec<u8> {
    let text = String::from_utf8_lossy(base).into_owned();
    match kind {
        Kind::Json => {
            let mut lines: Vec<&str> = text.lines().collect();
            let need = "\"$comment\": \"Installed by bedrock v";
            if lines.len() > 1 && lines[0] == "{" && lines[1].trim_start().starts_with(need) {
                lines.remove(1);
            }
            let mut s = lines.join("\n");
            if text.ends_with('\n') {
                s.push('\n');
            }
            s.into_bytes()
        }
        _ => {
            for p in ["# Installed by bedrock v", "# seeded by bedrock v"] {
                if let Some(rest) = text.strip_prefix(p)
                    && let Some(idx) = rest.find('\n')
                {
                    return rest[idx + 1..].to_string().into_bytes();
                }
            }
            text.into_bytes()
        }
    }
}

/// Write a file in canonical stamped form for the current version; true when
/// it wrote (absent or differing). `bedrock update` refreshes the installed
/// base files through this.
pub fn write_stamped(kind: Kind, path: &Path, bytes: &[u8]) -> Result<bool, Fatal> {
    let stamped = render(kind, current_version(), bytes);
    if let Ok(existing) = std::fs::read(path) {
        if existing == stamped {
            return Ok(false);
        }
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| Fatal(format!("cannot create {}: {e}", parent.display())))?;
    }
    std::fs::write(path, &stamped)
        .map_err(|e| Fatal(format!("cannot write {}: {e}", path.display())))?;
    Ok(true)
}

/// Read a file's bytes, returned as its canonical stamped form for the
/// current version (used by install paths that re-read a copied file).
pub fn stamped_file(kind: Kind, path: &Path) -> Result<Vec<u8>, Fatal> {
    let bytes =
        std::fs::read(path).map_err(|e| Fatal(format!("cannot read {}: {e}", path.display())))?;
    Ok(render(kind, current_version(), &bytes))
}

/// Re-write `path` in canonical stamped form for the current version; true
/// when it wrote. Reads the current bytes first, so callers can stamp a file
/// that was just copied from a template seed.
pub fn stamp_path(kind: Kind, path: &Path) -> Result<bool, Fatal> {
    let bytes =
        std::fs::read(path).map_err(|e| Fatal(format!("cannot read {}: {e}", path.display())))?;
    write_stamped(kind, path, &bytes)
}
